
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BRANCH DEFAULT ID SPEAK STEP STRINGscript : script step\n              | stepstep : STEP ID blockblock : block statement\n             | statementstatement : SPEAK STRINGstatement : BRANCH STRING IDstatement : DEFAULT ID'
    
_lr_action_items = {'STEP':([0,1,2,4,6,7,11,12,14,15,],[3,3,-2,-1,-3,-5,-4,-6,-8,-7,]),'$end':([1,2,4,6,7,11,12,14,15,],[0,-2,-1,-3,-5,-4,-6,-8,-7,]),'ID':([3,10,13,],[5,14,15,]),'SPEAK':([5,6,7,11,12,14,15,],[8,8,-5,-4,-6,-8,-7,]),'BRANCH':([5,6,7,11,12,14,15,],[9,9,-5,-4,-6,-8,-7,]),'DEFAULT':([5,6,7,11,12,14,15,],[10,10,-5,-4,-6,-8,-7,]),'STRING':([8,9,],[12,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'script':([0,],[1,]),'step':([0,1,],[2,4,]),'block':([5,],[6,]),'statement':([5,6,],[7,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> script","S'",1,None,None,None),
  ('script -> script step','script',2,'p_script','parser.py',36),
  ('script -> step','script',1,'p_script','parser.py',37),
  ('step -> STEP ID block','step',3,'p_step','parser.py',42),
  ('block -> block statement','block',2,'p_block','parser.py',47),
  ('block -> statement','block',1,'p_block','parser.py',48),
  ('statement -> SPEAK STRING','statement',2,'p_statement_speak','parser.py',53),
  ('statement -> BRANCH STRING ID','statement',3,'p_statement_branch','parser.py',58),
  ('statement -> DEFAULT ID','statement',2,'p_statement_default','parser.py',63),
]
